version: 1
# Don't touch the version number
settings:
  checkhours: 0
  checkminutes: 0
  checkseconds: 1
  # Setting all to zero will disable the automatic logger
  # Default is 1 second
  listtype: blacklist
  # Whether to use a blacklist or a whitelist, default is blacklist.
  # Blacklist prevents players from being logged, if whitelist is enabled then only specified people are logged
  shorten-log: false
  # Shortens the sentences of the logs
  bstats: true
specified-players:
